// Code generated by goctl. DO NOT EDIT.
package types

type PostInfo struct {
	UserInfo     UserSimpleInfo `json:"user_info"`
	Id           uint           `json:"id"`
	UserId       uint           `json:"user_id"`
	ContentCount uint           `json:"content_count"`
	LikeCount    uint           `json:"like_count"`
	CollectCount uint           `json:"collect_count"`
	Content      string         `json:"content"`
	ImageUrls    []string       `json:"image_urls"`
	CreateTime   int32          `json:"create_time"`
	DeleteTime   int32          `json:"delete_time"`
}

type UserSimpleInfo struct {
	Id          uint   `json:"user_id"`
	NickName    string `json:"nick_name"`
	Account     string `json:"account"`
	AvatarImage string `json:"avatar_image"`
}

type PostCreateRequest struct {
}

type PostCreateResponse struct {
	PostId uint `json:"post_id"`
}

type PostDelRequest struct {
	PostId uint `json:"post_id"`
}

type PostDelResponse struct {
}

type LookPostByOwnRequest struct {
}

type LookPostByOwnResponses struct {
	PostData []*PostInfo `json:"post_data"`
}

type LookAllPostsResponse struct {
	PostData []*PostInfo `json:"post_data"`
}

type LikePostRequest struct {
	PostId uint `json:"post_id"`
}

type LikePostResponse struct {
	LikeId uint `json:"like_id"`
}

type CancelLikePostRequest struct {
	LikeId uint `json:"like_id"`
	PostId uint `json:"post_id"`
}

type CancelLikePostResponse struct {
}

type CommentPostRequest struct {
	PostId  uint   `json:"post_id"`
	Content string `json:"content"`
}

type CommentPostResponse struct {
	CommentId uint `json:"comment_id"`
}

type CancelCommentPostRequest struct {
	PostId    uint `json:"post_id"`
	CommentId uint `json:"comment_id"`
}

type CancelCommentPostResponse struct {
}

type CollectPostRequest struct {
	PostId uint `json:"post_id"`
}

type CollectPostResponse struct {
	CollectId uint `json:"collect_id"`
}

type CancelCollectPostRequest struct {
	PostId    uint `json:"post_id"`
	CollectId uint `json:"collect_id"`
}

type CancelCollectPostResponse struct {
}

type CommentInfo struct {
	Id         uint           `json:"id"`
	CreateTime int32          `json:"create_time"`
	PostId     uint           `json:"post_id"`
	Comment    string         `json:"comment"`
	UserInfo   UserSimpleInfo `json:"user_info"`
}

type LookCommentRequest struct {
	PostId uint `json:"post_id"`
}

type LookCommentResponse struct {
	CommentData []*CommentInfo `json:"comment_data"`
}

type VerificationRequest struct {
	Email string `json:"email"`
}

type VerificationResponse struct {
}

type UserLoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UserLoginResponse struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
}

type JwtInfo struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
}

type UserRegisterRequest struct {
	Email     string `json:"email"`
	Password  string `json:"password"`
	EmailCode string `json:"email_code"`
}

type UserRegisterResponse struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type UserInfoResponse struct {
	Id               int64  `json:"id"`
	NickName         string `json:"nick_name"`
	Account          string `json:"account"`
	Email            string `json:"email"`
	AvatarBackground string `json:"avatar_background"`
	BackgroundImage  string `json:"background_image"`
	Phone            string `json:"phone"`
	PostCount        int64  `json:"post_count"`
	FollowCount      int64  `json:"follow_count"`
	FansCount        int64  `json:"fans_count"`
	LikeCount        int64  `json:"like_count"`
	PointCount       int64  `json:"point_count"`
}

type UserForgetPwdRequest struct {
	Email     string `json:"email"`
	EmailCode string `json:"email_code"`
}

type UserForgetPwdResponse struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
}

type UserModPwdRequset struct {
	Password string `json:"password"`
}

type UserModPwdResponse struct {
}

type UserModAvatarResponse struct {
}

type UserModBackgroundResponse struct {
}

type UserModInfoRequest struct {
	NickName string `json:"nick_name"`
	Phone    string `json:"phone"`
}

type UserModInfoResponse struct {
}

type UserPopularInfo struct {
	UserId    uint32 `json:"user_id"`
	NickName  string `json:"nick_name"`
	Account   string `json:"account"`
	LikeCount int64  `json:"like_count"`
	Avatar    string `json:"avatar"`
}

type UserPopularityRankingsRequest struct {
}

type UserPopularityRankingsResponse struct {
	UserPopularData []*UserPopularInfo `json:"user_popular_data"`
}

type PostPopularityInfo struct {
	PostId          uint32           `json:"post_id"`
	Content         string           `json:"content"`
	LikeCont        int64            `json:"like_count"`
	CollectionCount int64            `json:"collection_count"`
	CommentCount    int64            `json:"comment_count"`
	PopularInfo     *UserPopularInfo `json:"popular_info"`
	PostImage       []string         `json:"post_image"`
}

type PostPopularityRankingsRequest struct {
}

type PostPopularityRankingsResponse struct {
	PostPopularData []*PostPopularityInfo `json:"post_popular_data"`
}
