// Code generated by goctl. DO NOT EDIT.
package types

type VerificationRequest struct {
	Email string `json:"email"`
}

type VerificationResponse struct {
}

type UserLoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UserLoginResponse struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
}

type JwtInfo struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
}

type UserRegisterRequest struct {
	Email     string `json:"email"`
	Password  string `json:"password"`
	EmailCode string `json:"email_code"`
}

type UserRegisterResponse struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type UserInfoResponse struct {
	Id               int64  `json:"id"`
	NickName         string `json:"nick_name"`
	Account          string `json:"account"`
	Email            string `json:"email"`
	AvatarBackground string `json:"avatar_background"`
	BackgroundImage  string `json:"background_image"`
	Phone            string `json:"phone"`
}

type UserForgetPwdRequest struct {
	Email     string `json:"email"`
	EmailCode string `json:"email_code"`
}

type UserForgetPwdResponse struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
}

type UserModPwdRequset struct {
	Password string `json:"password"`
}

type UserModPwdResponse struct {
}

type UserModAvatarResponse struct {
}

type UserModBackgroundResponse struct {
}

type UserModInfoRequest struct {
	NickName string `json:"nick_name"`
	Phone    string `json:"phone"`
}

type UserModInfoResponse struct {
}
