Name: App
Host: 0.0.0.0
Port: 12000

Mysql:
  DataSource: root:root@tcp(127.0.0.1:3306)/wonderWriting?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai

CacheRedis:
  - Host: 127.0.0.1:6379
    Pass:
    Type: node

Auth:
  AccessSecret: uOvKLmVfztaXGpNYd4Z0I1SiT7MweJhl
  AccessExpire: 86400

UserRpc:
  Etcd:
    Hosts:
      - 127.0.0.1:2379
    Key: user.rpc


CommunityRpc:
  Etcd:
    Hosts:
      - 127.0.0.1:2379
    Key: community.rpc

HomeRpc:
  Etcd:
    Hosts:
      - 127.0.0.1:2379
    Key: home.rpc

GroupRpc:
  Etcd:
    Hosts:
      - 127.0.0.1:2379
    Key: group.rpc

ActivityRpc:
  Etcd:
    Hosts:
      - 127.0.0.1:2379
    Key: activity.rpc

KqPusherConf:
  Brokers:
    - 127.0.0.1:9092
  Topic: payment-success
#kq
KqConsumerConf:
  Name: kqConsumer
  Brokers:
    - 127.0.1:9092
  Group: kqConsumer
  Topic: payment-success
  Offset: first
  Consumers: 8
  Processors: 8