// Code generated by goctl. DO NOT EDIT.
// Source: community.proto

package server

import (
	"context"

	"calligraphy/apps/community/rpc/internal/logic"
	"calligraphy/apps/community/rpc/internal/svc"
	"calligraphy/apps/community/rpc/types/community"
)

type CommunityServer struct {
	svcCtx *svc.ServiceContext
	community.UnimplementedCommunityServer
}

func NewCommunityServer(svcCtx *svc.ServiceContext) *CommunityServer {
	return &CommunityServer{
		svcCtx: svcCtx,
	}
}

func (s *CommunityServer) CommunityCreatePost(ctx context.Context, in *community.CommunityCreatePostRequest) (*community.CommunityCreatePostResponse, error) {
	l := logic.NewCommunityCreatePostLogic(ctx, s.svcCtx)
	return l.CommunityCreatePost(in)
}

func (s *CommunityServer) CommunityDelPost(ctx context.Context, in *community.CommunityDelPostRequest) (*community.CommunityDelPostResponse, error) {
	l := logic.NewCommunityDelPostLogic(ctx, s.svcCtx)
	return l.CommunityDelPost(in)
}

func (s *CommunityServer) CommunityLookPostByOwn(ctx context.Context, in *community.CommunityLookPostByOwnRequest) (*community.CommunityLookPostByOwnResponses, error) {
	l := logic.NewCommunityLookPostByOwnLogic(ctx, s.svcCtx)
	return l.CommunityLookPostByOwn(in)
}

func (s *CommunityServer) CommunityLookAllPosts(ctx context.Context, in *community.CommunityLookAllPostsRequest) (*community.CommunityLookAllPostsResponse, error) {
	l := logic.NewCommunityLookAllPostsLogic(ctx, s.svcCtx)
	return l.CommunityLookAllPosts(in)
}
