// Code generated by goctl. DO NOT EDIT.
// Source: home.proto

package homeclient

import (
	"context"

	"calligraphy/apps/home/rpc/types/home"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	PostPopularityInfo             = home.PostPopularityInfo
	PostPopularityRankingsRequest  = home.PostPopularityRankingsRequest
	PostPopularityRankingsResponse = home.PostPopularityRankingsResponse
	UserPopularInfo                = home.UserPopularInfo
	UserPopularityRankingsRequest  = home.UserPopularityRankingsRequest
	UserPopularityRankingsResponse = home.UserPopularityRankingsResponse

	Home interface {
		// 帖子每日的排行榜
		PostPopularityRankings(ctx context.Context, in *PostPopularityRankingsRequest, opts ...grpc.CallOption) (*PostPopularityRankingsResponse, error)
		// 用户人气排行榜
		UserPopularityRankings(ctx context.Context, in *UserPopularityRankingsRequest, opts ...grpc.CallOption) (*UserPopularityRankingsResponse, error)
	}

	defaultHome struct {
		cli zrpc.Client
	}
)

func NewHome(cli zrpc.Client) Home {
	return &defaultHome{
		cli: cli,
	}
}

// 帖子每日的排行榜
func (m *defaultHome) PostPopularityRankings(ctx context.Context, in *PostPopularityRankingsRequest, opts ...grpc.CallOption) (*PostPopularityRankingsResponse, error) {
	client := home.NewHomeClient(m.cli.Conn())
	return client.PostPopularityRankings(ctx, in, opts...)
}

// 用户人气排行榜
func (m *defaultHome) UserPopularityRankings(ctx context.Context, in *UserPopularityRankingsRequest, opts ...grpc.CallOption) (*UserPopularityRankingsResponse, error) {
	client := home.NewHomeClient(m.cli.Conn())
	return client.UserPopularityRankings(ctx, in, opts...)
}
