// Code generated by goctl. DO NOT EDIT.
// Source: activity.proto

package server

import (
	"context"

	"calligraphy/apps/activity/rpc/internal/logic"
	"calligraphy/apps/activity/rpc/internal/svc"
	"calligraphy/apps/activity/rpc/types/activity"
)

type ActivityServer struct {
	svcCtx *svc.ServiceContext
	activity.UnimplementedActivityServer
}

func NewActivityServer(svcCtx *svc.ServiceContext) *ActivityServer {
	return &ActivityServer{
		svcCtx: svcCtx,
	}
}

func (s *ActivityServer) GrabPoints(ctx context.Context, in *activity.GrabPointsRequest) (*activity.GrabPointsResponse, error) {
	l := logic.NewGrabPointsLogic(ctx, s.svcCtx)
	return l.GrabPoints(in)
}
