// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.11.2
// source: rpc/home.proto

package home

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Home_PostPopularityRankings_FullMethodName = "/home.home/PostPopularityRankings"
	Home_UserPopularityRankings_FullMethodName = "/home.home/UserPopularityRankings"
)

// HomeClient is the client API for Home service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HomeClient interface {
	// 帖子每日的排行榜
	PostPopularityRankings(ctx context.Context, in *PostPopularityRankingsRequest, opts ...grpc.CallOption) (*PostPopularityRankingsResponse, error)
	UserPopularityRankings(ctx context.Context, in *UserPopularityRankingsRequest, opts ...grpc.CallOption) (*UserPopularityRankingsResponse, error)
}

type homeClient struct {
	cc grpc.ClientConnInterface
}

func NewHomeClient(cc grpc.ClientConnInterface) HomeClient {
	return &homeClient{cc}
}

func (c *homeClient) PostPopularityRankings(ctx context.Context, in *PostPopularityRankingsRequest, opts ...grpc.CallOption) (*PostPopularityRankingsResponse, error) {
	out := new(PostPopularityRankingsResponse)
	err := c.cc.Invoke(ctx, Home_PostPopularityRankings_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *homeClient) UserPopularityRankings(ctx context.Context, in *UserPopularityRankingsRequest, opts ...grpc.CallOption) (*UserPopularityRankingsResponse, error) {
	out := new(UserPopularityRankingsResponse)
	err := c.cc.Invoke(ctx, Home_UserPopularityRankings_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HomeServer is the server API for Home service.
// All implementations must embed UnimplementedHomeServer
// for forward compatibility
type HomeServer interface {
	// 帖子每日的排行榜
	PostPopularityRankings(context.Context, *PostPopularityRankingsRequest) (*PostPopularityRankingsResponse, error)
	UserPopularityRankings(context.Context, *UserPopularityRankingsRequest) (*UserPopularityRankingsResponse, error)
	mustEmbedUnimplementedHomeServer()
}

// UnimplementedHomeServer must be embedded to have forward compatible implementations.
type UnimplementedHomeServer struct {
}

func (UnimplementedHomeServer) PostPopularityRankings(context.Context, *PostPopularityRankingsRequest) (*PostPopularityRankingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostPopularityRankings not implemented")
}
func (UnimplementedHomeServer) UserPopularityRankings(context.Context, *UserPopularityRankingsRequest) (*UserPopularityRankingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserPopularityRankings not implemented")
}
func (UnimplementedHomeServer) mustEmbedUnimplementedHomeServer() {}

// UnsafeHomeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HomeServer will
// result in compilation errors.
type UnsafeHomeServer interface {
	mustEmbedUnimplementedHomeServer()
}

func RegisterHomeServer(s grpc.ServiceRegistrar, srv HomeServer) {
	s.RegisterService(&Home_ServiceDesc, srv)
}

func _Home_PostPopularityRankings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostPopularityRankingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomeServer).PostPopularityRankings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Home_PostPopularityRankings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomeServer).PostPopularityRankings(ctx, req.(*PostPopularityRankingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Home_UserPopularityRankings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserPopularityRankingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomeServer).UserPopularityRankings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Home_UserPopularityRankings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomeServer).UserPopularityRankings(ctx, req.(*UserPopularityRankingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Home_ServiceDesc is the grpc.ServiceDesc for Home service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Home_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "home.home",
	HandlerType: (*HomeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostPopularityRankings",
			Handler:    _Home_PostPopularityRankings_Handler,
		},
		{
			MethodName: "UserPopularityRankings",
			Handler:    _Home_UserPopularityRankings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/home.proto",
}
