// Code generated by goctl. DO NOT EDIT.
// Source: home.proto

package server

import (
	"context"

	"calligraphy/apps/home/rpc/internal/logic"
	"calligraphy/apps/home/rpc/internal/svc"
	"calligraphy/apps/home/rpc/types/home"
)

type HomeServer struct {
	svcCtx *svc.ServiceContext
	home.UnimplementedHomeServer
}

func NewHomeServer(svcCtx *svc.ServiceContext) *HomeServer {
	return &HomeServer{
		svcCtx: svcCtx,
	}
}

// 帖子每日的排行榜
func (s *HomeServer) PostPopularityRankings(ctx context.Context, in *home.PostPopularityRankingsRequest) (*home.PostPopularityRankingsResponse, error) {
	l := logic.NewPostPopularityRankingsLogic(ctx, s.svcCtx)
	return l.PostPopularityRankings(in)
}

func (s *HomeServer) UserPopularityRankings(ctx context.Context, in *home.UserPopularityRankingsRequest) (*home.UserPopularityRankingsResponse, error) {
	l := logic.NewUserPopularityRankingsLogic(ctx, s.svcCtx)
	return l.UserPopularityRankings(in)
}
