// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.11.2
// source: rpc/community.proto

package community

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 帖子信息
type PostInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint32   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	UserId       uint32   `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	LikeCount    uint32   `protobuf:"varint,3,opt,name=LikeCount,proto3" json:"LikeCount,omitempty"`
	Content      string   `protobuf:"bytes,4,opt,name=Content,proto3" json:"Content,omitempty"`
	ImageUrls    []string `protobuf:"bytes,5,rep,name=Image_urls,json=ImageUrls,proto3" json:"Image_urls,omitempty"`
	CreateTime   uint32   `protobuf:"varint,6,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"` //创建时间
	DeleteTime   uint32   `protobuf:"varint,7,opt,name=DeleteTime,proto3" json:"DeleteTime,omitempty"` //删除时间
	ContentCount uint32   `protobuf:"varint,8,opt,name=ContentCount,proto3" json:"ContentCount,omitempty"`
	CollectCount uint32   `protobuf:"varint,9,opt,name=CollectCount,proto3" json:"CollectCount,omitempty"`
}

func (x *PostInfo) Reset() {
	*x = PostInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_community_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInfo) ProtoMessage() {}

func (x *PostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_community_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInfo.ProtoReflect.Descriptor instead.
func (*PostInfo) Descriptor() ([]byte, []int) {
	return file_rpc_community_proto_rawDescGZIP(), []int{0}
}

func (x *PostInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PostInfo) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PostInfo) GetLikeCount() uint32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *PostInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PostInfo) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *PostInfo) GetCreateTime() uint32 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *PostInfo) GetDeleteTime() uint32 {
	if x != nil {
		return x.DeleteTime
	}
	return 0
}

func (x *PostInfo) GetContentCount() uint32 {
	if x != nil {
		return x.ContentCount
	}
	return 0
}

func (x *PostInfo) GetCollectCount() uint32 {
	if x != nil {
		return x.CollectCount
	}
	return 0
}

// 帖子创建
type CommunityCreatePostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    uint32   `protobuf:"varint,3,opt,name=User_id,json=UserId,proto3" json:"User_id,omitempty"`
	Content   string   `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	ImageUrls []string `protobuf:"bytes,2,rep,name=Image_urls,json=ImageUrls,proto3" json:"Image_urls,omitempty"`
}

func (x *CommunityCreatePostRequest) Reset() {
	*x = CommunityCreatePostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_community_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommunityCreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityCreatePostRequest) ProtoMessage() {}

func (x *CommunityCreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_community_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityCreatePostRequest.ProtoReflect.Descriptor instead.
func (*CommunityCreatePostRequest) Descriptor() ([]byte, []int) {
	return file_rpc_community_proto_rawDescGZIP(), []int{1}
}

func (x *CommunityCreatePostRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CommunityCreatePostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommunityCreatePostRequest) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

type CommunityCreatePostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 可以添加一些返回信息字段，比如返回的帖子ID等
	PostId uint32 `protobuf:"varint,1,opt,name=PostId,proto3" json:"PostId,omitempty"`
}

func (x *CommunityCreatePostResponse) Reset() {
	*x = CommunityCreatePostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_community_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommunityCreatePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityCreatePostResponse) ProtoMessage() {}

func (x *CommunityCreatePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_community_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityCreatePostResponse.ProtoReflect.Descriptor instead.
func (*CommunityCreatePostResponse) Descriptor() ([]byte, []int) {
	return file_rpc_community_proto_rawDescGZIP(), []int{2}
}

func (x *CommunityCreatePostResponse) GetPostId() uint32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

// 帖子删除
type CommunityDelPostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId uint32 `protobuf:"varint,1,opt,name=PostId,proto3" json:"PostId,omitempty"`
}

func (x *CommunityDelPostRequest) Reset() {
	*x = CommunityDelPostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_community_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommunityDelPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityDelPostRequest) ProtoMessage() {}

func (x *CommunityDelPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_community_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityDelPostRequest.ProtoReflect.Descriptor instead.
func (*CommunityDelPostRequest) Descriptor() ([]byte, []int) {
	return file_rpc_community_proto_rawDescGZIP(), []int{3}
}

func (x *CommunityDelPostRequest) GetPostId() uint32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type CommunityDelPostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CommunityDelPostResponse) Reset() {
	*x = CommunityDelPostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_community_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommunityDelPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityDelPostResponse) ProtoMessage() {}

func (x *CommunityDelPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_community_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityDelPostResponse.ProtoReflect.Descriptor instead.
func (*CommunityDelPostResponse) Descriptor() ([]byte, []int) {
	return file_rpc_community_proto_rawDescGZIP(), []int{4}
}

// 查看自己的所有帖子
type CommunityLookPostByOwnRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint32 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
}

func (x *CommunityLookPostByOwnRequest) Reset() {
	*x = CommunityLookPostByOwnRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_community_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommunityLookPostByOwnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityLookPostByOwnRequest) ProtoMessage() {}

func (x *CommunityLookPostByOwnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_community_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityLookPostByOwnRequest.ProtoReflect.Descriptor instead.
func (*CommunityLookPostByOwnRequest) Descriptor() ([]byte, []int) {
	return file_rpc_community_proto_rawDescGZIP(), []int{5}
}

func (x *CommunityLookPostByOwnRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CommunityLookPostByOwnResponses struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostData []*PostInfo `protobuf:"bytes,1,rep,name=PostData,proto3" json:"PostData,omitempty"`
}

func (x *CommunityLookPostByOwnResponses) Reset() {
	*x = CommunityLookPostByOwnResponses{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_community_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommunityLookPostByOwnResponses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityLookPostByOwnResponses) ProtoMessage() {}

func (x *CommunityLookPostByOwnResponses) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_community_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityLookPostByOwnResponses.ProtoReflect.Descriptor instead.
func (*CommunityLookPostByOwnResponses) Descriptor() ([]byte, []int) {
	return file_rpc_community_proto_rawDescGZIP(), []int{6}
}

func (x *CommunityLookPostByOwnResponses) GetPostData() []*PostInfo {
	if x != nil {
		return x.PostData
	}
	return nil
}

// 用户查看所有的帖子
type CommunityLookAllPostsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CommunityLookAllPostsRequest) Reset() {
	*x = CommunityLookAllPostsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_community_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommunityLookAllPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityLookAllPostsRequest) ProtoMessage() {}

func (x *CommunityLookAllPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_community_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityLookAllPostsRequest.ProtoReflect.Descriptor instead.
func (*CommunityLookAllPostsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_community_proto_rawDescGZIP(), []int{7}
}

type CommunityLookAllPostsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostData []*PostInfo `protobuf:"bytes,1,rep,name=PostData,proto3" json:"PostData,omitempty"`
}

func (x *CommunityLookAllPostsResponse) Reset() {
	*x = CommunityLookAllPostsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_community_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommunityLookAllPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityLookAllPostsResponse) ProtoMessage() {}

func (x *CommunityLookAllPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_community_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityLookAllPostsResponse.ProtoReflect.Descriptor instead.
func (*CommunityLookAllPostsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_community_proto_rawDescGZIP(), []int{8}
}

func (x *CommunityLookAllPostsResponse) GetPostData() []*PostInfo {
	if x != nil {
		return x.PostData
	}
	return nil
}

// 点赞帖子
type CommunityLikePostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint32 `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	PostId uint32 `protobuf:"varint,1,opt,name=PostId,proto3" json:"PostId,omitempty"`
}

func (x *CommunityLikePostRequest) Reset() {
	*x = CommunityLikePostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_community_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommunityLikePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityLikePostRequest) ProtoMessage() {}

func (x *CommunityLikePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_community_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityLikePostRequest.ProtoReflect.Descriptor instead.
func (*CommunityLikePostRequest) Descriptor() ([]byte, []int) {
	return file_rpc_community_proto_rawDescGZIP(), []int{9}
}

func (x *CommunityLikePostRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CommunityLikePostRequest) GetPostId() uint32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type CommunityLikePostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LikeId uint32 `protobuf:"varint,1,opt,name=LikeId,proto3" json:"LikeId,omitempty"`
}

func (x *CommunityLikePostResponse) Reset() {
	*x = CommunityLikePostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_community_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommunityLikePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityLikePostResponse) ProtoMessage() {}

func (x *CommunityLikePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_community_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityLikePostResponse.ProtoReflect.Descriptor instead.
func (*CommunityLikePostResponse) Descriptor() ([]byte, []int) {
	return file_rpc_community_proto_rawDescGZIP(), []int{10}
}

func (x *CommunityLikePostResponse) GetLikeId() uint32 {
	if x != nil {
		return x.LikeId
	}
	return 0
}

// 取消点赞
type CommunityCancelLikePostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LikeId uint32 `protobuf:"varint,1,opt,name=LikeId,proto3" json:"LikeId,omitempty"`
	UserId uint32 `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	PostId uint32 `protobuf:"varint,3,opt,name=PostId,proto3" json:"PostId,omitempty"`
}

func (x *CommunityCancelLikePostRequest) Reset() {
	*x = CommunityCancelLikePostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_community_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommunityCancelLikePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityCancelLikePostRequest) ProtoMessage() {}

func (x *CommunityCancelLikePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_community_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityCancelLikePostRequest.ProtoReflect.Descriptor instead.
func (*CommunityCancelLikePostRequest) Descriptor() ([]byte, []int) {
	return file_rpc_community_proto_rawDescGZIP(), []int{11}
}

func (x *CommunityCancelLikePostRequest) GetLikeId() uint32 {
	if x != nil {
		return x.LikeId
	}
	return 0
}

func (x *CommunityCancelLikePostRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CommunityCancelLikePostRequest) GetPostId() uint32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type CommunityCancelLikePostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CommunityCancelLikePostResponse) Reset() {
	*x = CommunityCancelLikePostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_community_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommunityCancelLikePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityCancelLikePostResponse) ProtoMessage() {}

func (x *CommunityCancelLikePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_community_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityCancelLikePostResponse.ProtoReflect.Descriptor instead.
func (*CommunityCancelLikePostResponse) Descriptor() ([]byte, []int) {
	return file_rpc_community_proto_rawDescGZIP(), []int{12}
}

// 收藏帖子
type CommunityCollectPostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId uint32 `protobuf:"varint,1,opt,name=PostId,proto3" json:"PostId,omitempty"`
	UserId uint32 `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
}

func (x *CommunityCollectPostRequest) Reset() {
	*x = CommunityCollectPostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_community_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommunityCollectPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityCollectPostRequest) ProtoMessage() {}

func (x *CommunityCollectPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_community_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityCollectPostRequest.ProtoReflect.Descriptor instead.
func (*CommunityCollectPostRequest) Descriptor() ([]byte, []int) {
	return file_rpc_community_proto_rawDescGZIP(), []int{13}
}

func (x *CommunityCollectPostRequest) GetPostId() uint32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *CommunityCollectPostRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CommunityCollectPostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CollectId uint32 `protobuf:"varint,1,opt,name=CollectId,proto3" json:"CollectId,omitempty"`
}

func (x *CommunityCollectPostResponse) Reset() {
	*x = CommunityCollectPostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_community_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommunityCollectPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityCollectPostResponse) ProtoMessage() {}

func (x *CommunityCollectPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_community_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityCollectPostResponse.ProtoReflect.Descriptor instead.
func (*CommunityCollectPostResponse) Descriptor() ([]byte, []int) {
	return file_rpc_community_proto_rawDescGZIP(), []int{14}
}

func (x *CommunityCollectPostResponse) GetCollectId() uint32 {
	if x != nil {
		return x.CollectId
	}
	return 0
}

// 取消收藏
type CommunityCancelCollectPostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CollectId uint32 `protobuf:"varint,1,opt,name=CollectId,proto3" json:"CollectId,omitempty"`
	UserId    uint32 `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	PostId    uint32 `protobuf:"varint,3,opt,name=PostId,proto3" json:"PostId,omitempty"`
}

func (x *CommunityCancelCollectPostRequest) Reset() {
	*x = CommunityCancelCollectPostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_community_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommunityCancelCollectPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityCancelCollectPostRequest) ProtoMessage() {}

func (x *CommunityCancelCollectPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_community_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityCancelCollectPostRequest.ProtoReflect.Descriptor instead.
func (*CommunityCancelCollectPostRequest) Descriptor() ([]byte, []int) {
	return file_rpc_community_proto_rawDescGZIP(), []int{15}
}

func (x *CommunityCancelCollectPostRequest) GetCollectId() uint32 {
	if x != nil {
		return x.CollectId
	}
	return 0
}

func (x *CommunityCancelCollectPostRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CommunityCancelCollectPostRequest) GetPostId() uint32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type CommunityCancelCollectPostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CommunityCancelCollectPostResponse) Reset() {
	*x = CommunityCancelCollectPostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_community_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommunityCancelCollectPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityCancelCollectPostResponse) ProtoMessage() {}

func (x *CommunityCancelCollectPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_community_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityCancelCollectPostResponse.ProtoReflect.Descriptor instead.
func (*CommunityCancelCollectPostResponse) Descriptor() ([]byte, []int) {
	return file_rpc_community_proto_rawDescGZIP(), []int{16}
}

// 评论帖子
type CommunityContentPostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId  uint32 `protobuf:"varint,1,opt,name=PostId,proto3" json:"PostId,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
	UserId  uint32 `protobuf:"varint,3,opt,name=UserId,proto3" json:"UserId,omitempty"`
}

func (x *CommunityContentPostRequest) Reset() {
	*x = CommunityContentPostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_community_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommunityContentPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityContentPostRequest) ProtoMessage() {}

func (x *CommunityContentPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_community_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityContentPostRequest.ProtoReflect.Descriptor instead.
func (*CommunityContentPostRequest) Descriptor() ([]byte, []int) {
	return file_rpc_community_proto_rawDescGZIP(), []int{17}
}

func (x *CommunityContentPostRequest) GetPostId() uint32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *CommunityContentPostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommunityContentPostRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CommunityContentPostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContentId uint32 `protobuf:"varint,1,opt,name=ContentId,proto3" json:"ContentId,omitempty"`
}

func (x *CommunityContentPostResponse) Reset() {
	*x = CommunityContentPostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_community_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommunityContentPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityContentPostResponse) ProtoMessage() {}

func (x *CommunityContentPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_community_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityContentPostResponse.ProtoReflect.Descriptor instead.
func (*CommunityContentPostResponse) Descriptor() ([]byte, []int) {
	return file_rpc_community_proto_rawDescGZIP(), []int{18}
}

func (x *CommunityContentPostResponse) GetContentId() uint32 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

// 取消评论
type CommunityCancelContentPostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContentId uint32 `protobuf:"varint,1,opt,name=ContentId,proto3" json:"ContentId,omitempty"`
	UserId    uint32 `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	PostId    uint32 `protobuf:"varint,3,opt,name=PostId,proto3" json:"PostId,omitempty"`
}

func (x *CommunityCancelContentPostRequest) Reset() {
	*x = CommunityCancelContentPostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_community_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommunityCancelContentPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityCancelContentPostRequest) ProtoMessage() {}

func (x *CommunityCancelContentPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_community_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityCancelContentPostRequest.ProtoReflect.Descriptor instead.
func (*CommunityCancelContentPostRequest) Descriptor() ([]byte, []int) {
	return file_rpc_community_proto_rawDescGZIP(), []int{19}
}

func (x *CommunityCancelContentPostRequest) GetContentId() uint32 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

func (x *CommunityCancelContentPostRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CommunityCancelContentPostRequest) GetPostId() uint32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type CommunityCancelContentPostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CommunityCancelContentPostResponse) Reset() {
	*x = CommunityCancelContentPostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_community_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommunityCancelContentPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityCancelContentPostResponse) ProtoMessage() {}

func (x *CommunityCancelContentPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_community_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityCancelContentPostResponse.ProtoReflect.Descriptor instead.
func (*CommunityCancelContentPostResponse) Descriptor() ([]byte, []int) {
	return file_rpc_community_proto_rawDescGZIP(), []int{20}
}

var File_rpc_community_proto protoreflect.FileDescriptor

var file_rpc_community_proto_rawDesc = []byte{
	0x0a, 0x13, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79,
	0x22, 0x91, 0x02, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x4c, 0x69, 0x6b, 0x65, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x4c, 0x69, 0x6b, 0x65, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x09, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x73, 0x12, 0x1e, 0x0a, 0x0a,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0c, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x22, 0x0a, 0x0c, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x6e, 0x0a, 0x1a, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74,
	0x79, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75,
	0x72, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x55, 0x72, 0x6c, 0x73, 0x22, 0x35, 0x0a, 0x1b, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74,
	0x79, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x17, 0x43,
	0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x44, 0x65, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x22, 0x1a,
	0x0a, 0x18, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x44, 0x65, 0x6c, 0x50, 0x6f,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x37, 0x0a, 0x1d, 0x43, 0x6f,
	0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x4c, 0x6f, 0x6f, 0x6b, 0x50, 0x6f, 0x73, 0x74, 0x42,
	0x79, 0x4f, 0x77, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x52, 0x0a, 0x1f, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79,
	0x4c, 0x6f, 0x6f, 0x6b, 0x50, 0x6f, 0x73, 0x74, 0x42, 0x79, 0x4f, 0x77, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75,
	0x6e, 0x69, 0x74, 0x79, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x50,
	0x6f, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x22, 0x1e, 0x0a, 0x1c, 0x43, 0x6f, 0x6d, 0x6d, 0x75,
	0x6e, 0x69, 0x74, 0x79, 0x4c, 0x6f, 0x6f, 0x6b, 0x41, 0x6c, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x50, 0x0a, 0x1d, 0x43, 0x6f, 0x6d, 0x6d, 0x75,
	0x6e, 0x69, 0x74, 0x79, 0x4c, 0x6f, 0x6f, 0x6b, 0x41, 0x6c, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x08, 0x50, 0x6f, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x22, 0x4a, 0x0a, 0x18, 0x43, 0x6f, 0x6d,
	0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x6b, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x50,
	0x6f, 0x73, 0x74, 0x49, 0x64, 0x22, 0x33, 0x0a, 0x19, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69,
	0x74, 0x79, 0x4c, 0x69, 0x6b, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x4c, 0x69, 0x6b, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x4c, 0x69, 0x6b, 0x65, 0x49, 0x64, 0x22, 0x68, 0x0a, 0x1e, 0x43, 0x6f,
	0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x4c, 0x69, 0x6b,
	0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x4c, 0x69, 0x6b, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x4c, 0x69,
	0x6b, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x50, 0x6f,
	0x73, 0x74, 0x49, 0x64, 0x22, 0x21, 0x0a, 0x1f, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74,
	0x79, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x4c, 0x69, 0x6b, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4d, 0x0a, 0x1b, 0x43, 0x6f, 0x6d, 0x6d, 0x75,
	0x6e, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3c, 0x0a, 0x1c, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e,
	0x69, 0x74, 0x79, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x43, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x49, 0x64, 0x22, 0x71, 0x0a, 0x21, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74,
	0x79, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x50, 0x6f,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x43, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x22, 0x24, 0x0a, 0x22, 0x43, 0x6f, 0x6d, 0x6d, 0x75,
	0x6e, 0x69, 0x74, 0x79, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x67, 0x0a,
	0x1b, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x50, 0x6f,
	0x73, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3c, 0x0a, 0x1c, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e,
	0x69, 0x74, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x22, 0x71, 0x0a, 0x21, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74,
	0x79, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x50, 0x6f,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x22, 0x24, 0x0a, 0x22, 0x43, 0x6f, 0x6d, 0x6d, 0x75,
	0x6e, 0x69, 0x74, 0x79, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x8e, 0x08,
	0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x12, 0x55, 0x0a, 0x08, 0x4c,
	0x69, 0x6b, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x23, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e,
	0x69, 0x74, 0x79, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x6b,
	0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69,
	0x74, 0x79, 0x4c, 0x69, 0x6b, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x67, 0x0a, 0x0e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x4c, 0x69, 0x6b, 0x65,
	0x50, 0x6f, 0x73, 0x74, 0x12, 0x29, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c,
	0x4c, 0x69, 0x6b, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2a, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x2e, 0x43, 0x6f, 0x6d, 0x6d,
	0x75, 0x6e, 0x69, 0x74, 0x79, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x4c, 0x69, 0x6b, 0x65, 0x50,
	0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5e, 0x0a, 0x0b, 0x43,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x26, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79,
	0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x27, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x50,
	0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x70, 0x0a, 0x11, 0x43,
	0x61, 0x6e, 0x63, 0x65, 0x6c, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x50, 0x6f, 0x73, 0x74,
	0x12, 0x2c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x43, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x75,
	0x6e, 0x69, 0x74, 0x79, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5e, 0x0a,
	0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x26, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69,
	0x74, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x70, 0x0a,
	0x11, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x6f,
	0x73, 0x74, 0x12, 0x2c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x2d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x64, 0x0a, 0x13, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x25, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69,
	0x74, 0x79, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e,
	0x69, 0x74, 0x79, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5b, 0x0a, 0x10, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69,
	0x74, 0x79, 0x44, 0x65, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x22, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x75, 0x6e, 0x69, 0x74, 0x79, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x44,
	0x65, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e,
	0x69, 0x74, 0x79, 0x44, 0x65, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x6e, 0x0a, 0x16, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x4c,
	0x6f, 0x6f, 0x6b, 0x50, 0x6f, 0x73, 0x74, 0x42, 0x79, 0x4f, 0x77, 0x6e, 0x12, 0x28, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69,
	0x74, 0x79, 0x4c, 0x6f, 0x6f, 0x6b, 0x50, 0x6f, 0x73, 0x74, 0x42, 0x79, 0x4f, 0x77, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69,
	0x74, 0x79, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x4c, 0x6f, 0x6f, 0x6b,
	0x50, 0x6f, 0x73, 0x74, 0x42, 0x79, 0x4f, 0x77, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x73, 0x12, 0x6a, 0x0a, 0x15, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x4c,
	0x6f, 0x6f, 0x6b, 0x41, 0x6c, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x12, 0x27, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74,
	0x79, 0x4c, 0x6f, 0x6f, 0x6b, 0x41, 0x6c, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x4c, 0x6f, 0x6f, 0x6b, 0x41, 0x6c,
	0x6c, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0d,
	0x5a, 0x0b, 0x2e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_community_proto_rawDescOnce sync.Once
	file_rpc_community_proto_rawDescData = file_rpc_community_proto_rawDesc
)

func file_rpc_community_proto_rawDescGZIP() []byte {
	file_rpc_community_proto_rawDescOnce.Do(func() {
		file_rpc_community_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_community_proto_rawDescData)
	})
	return file_rpc_community_proto_rawDescData
}

var file_rpc_community_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_rpc_community_proto_goTypes = []interface{}{
	(*PostInfo)(nil),                           // 0: community.PostInfo
	(*CommunityCreatePostRequest)(nil),         // 1: community.CommunityCreatePostRequest
	(*CommunityCreatePostResponse)(nil),        // 2: community.CommunityCreatePostResponse
	(*CommunityDelPostRequest)(nil),            // 3: community.CommunityDelPostRequest
	(*CommunityDelPostResponse)(nil),           // 4: community.CommunityDelPostResponse
	(*CommunityLookPostByOwnRequest)(nil),      // 5: community.CommunityLookPostByOwnRequest
	(*CommunityLookPostByOwnResponses)(nil),    // 6: community.CommunityLookPostByOwnResponses
	(*CommunityLookAllPostsRequest)(nil),       // 7: community.CommunityLookAllPostsRequest
	(*CommunityLookAllPostsResponse)(nil),      // 8: community.CommunityLookAllPostsResponse
	(*CommunityLikePostRequest)(nil),           // 9: community.CommunityLikePostRequest
	(*CommunityLikePostResponse)(nil),          // 10: community.CommunityLikePostResponse
	(*CommunityCancelLikePostRequest)(nil),     // 11: community.CommunityCancelLikePostRequest
	(*CommunityCancelLikePostResponse)(nil),    // 12: community.CommunityCancelLikePostResponse
	(*CommunityCollectPostRequest)(nil),        // 13: community.CommunityCollectPostRequest
	(*CommunityCollectPostResponse)(nil),       // 14: community.CommunityCollectPostResponse
	(*CommunityCancelCollectPostRequest)(nil),  // 15: community.CommunityCancelCollectPostRequest
	(*CommunityCancelCollectPostResponse)(nil), // 16: community.CommunityCancelCollectPostResponse
	(*CommunityContentPostRequest)(nil),        // 17: community.CommunityContentPostRequest
	(*CommunityContentPostResponse)(nil),       // 18: community.CommunityContentPostResponse
	(*CommunityCancelContentPostRequest)(nil),  // 19: community.CommunityCancelContentPostRequest
	(*CommunityCancelContentPostResponse)(nil), // 20: community.CommunityCancelContentPostResponse
}
var file_rpc_community_proto_depIdxs = []int32{
	0,  // 0: community.CommunityLookPostByOwnResponses.PostData:type_name -> community.PostInfo
	0,  // 1: community.CommunityLookAllPostsResponse.PostData:type_name -> community.PostInfo
	9,  // 2: community.Community.LikePost:input_type -> community.CommunityLikePostRequest
	11, // 3: community.Community.CancelLikePost:input_type -> community.CommunityCancelLikePostRequest
	13, // 4: community.Community.CollectPost:input_type -> community.CommunityCollectPostRequest
	15, // 5: community.Community.CancelCollectPost:input_type -> community.CommunityCancelCollectPostRequest
	17, // 6: community.Community.CommentPost:input_type -> community.CommunityContentPostRequest
	19, // 7: community.Community.CancelCommentPost:input_type -> community.CommunityCancelContentPostRequest
	1,  // 8: community.Community.CommunityCreatePost:input_type -> community.CommunityCreatePostRequest
	3,  // 9: community.Community.CommunityDelPost:input_type -> community.CommunityDelPostRequest
	5,  // 10: community.Community.CommunityLookPostByOwn:input_type -> community.CommunityLookPostByOwnRequest
	7,  // 11: community.Community.CommunityLookAllPosts:input_type -> community.CommunityLookAllPostsRequest
	10, // 12: community.Community.LikePost:output_type -> community.CommunityLikePostResponse
	12, // 13: community.Community.CancelLikePost:output_type -> community.CommunityCancelLikePostResponse
	14, // 14: community.Community.CollectPost:output_type -> community.CommunityCollectPostResponse
	16, // 15: community.Community.CancelCollectPost:output_type -> community.CommunityCancelCollectPostResponse
	18, // 16: community.Community.CommentPost:output_type -> community.CommunityContentPostResponse
	20, // 17: community.Community.CancelCommentPost:output_type -> community.CommunityCancelContentPostResponse
	2,  // 18: community.Community.CommunityCreatePost:output_type -> community.CommunityCreatePostResponse
	4,  // 19: community.Community.CommunityDelPost:output_type -> community.CommunityDelPostResponse
	6,  // 20: community.Community.CommunityLookPostByOwn:output_type -> community.CommunityLookPostByOwnResponses
	8,  // 21: community.Community.CommunityLookAllPosts:output_type -> community.CommunityLookAllPostsResponse
	12, // [12:22] is the sub-list for method output_type
	2,  // [2:12] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_community_proto_init() }
func file_rpc_community_proto_init() {
	if File_rpc_community_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_community_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_community_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommunityCreatePostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_community_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommunityCreatePostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_community_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommunityDelPostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_community_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommunityDelPostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_community_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommunityLookPostByOwnRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_community_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommunityLookPostByOwnResponses); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_community_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommunityLookAllPostsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_community_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommunityLookAllPostsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_community_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommunityLikePostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_community_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommunityLikePostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_community_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommunityCancelLikePostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_community_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommunityCancelLikePostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_community_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommunityCollectPostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_community_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommunityCollectPostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_community_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommunityCancelCollectPostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_community_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommunityCancelCollectPostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_community_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommunityContentPostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_community_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommunityContentPostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_community_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommunityCancelContentPostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_community_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommunityCancelContentPostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_community_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_community_proto_goTypes,
		DependencyIndexes: file_rpc_community_proto_depIdxs,
		MessageInfos:      file_rpc_community_proto_msgTypes,
	}.Build()
	File_rpc_community_proto = out.File
	file_rpc_community_proto_rawDesc = nil
	file_rpc_community_proto_goTypes = nil
	file_rpc_community_proto_depIdxs = nil
}
