// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.11.2
// source: rpc/community.proto

package community

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 帖子信息
type PostInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         uint32   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	UserId     uint32   `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	LikeCount  uint32   `protobuf:"varint,3,opt,name=LikeCount,proto3" json:"LikeCount,omitempty"`
	Content    string   `protobuf:"bytes,4,opt,name=Content,proto3" json:"Content,omitempty"`
	ImageUrls  []string `protobuf:"bytes,5,rep,name=Image_urls,json=ImageUrls,proto3" json:"Image_urls,omitempty"`
	CreateTime uint32   `protobuf:"varint,6,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"` //创建时间
	DeleteTime uint32   `protobuf:"varint,7,opt,name=DeleteTime,proto3" json:"DeleteTime,omitempty"` //删除时间
}

func (x *PostInfo) Reset() {
	*x = PostInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_community_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInfo) ProtoMessage() {}

func (x *PostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_community_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInfo.ProtoReflect.Descriptor instead.
func (*PostInfo) Descriptor() ([]byte, []int) {
	return file_rpc_community_proto_rawDescGZIP(), []int{0}
}

func (x *PostInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PostInfo) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PostInfo) GetLikeCount() uint32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *PostInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PostInfo) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *PostInfo) GetCreateTime() uint32 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *PostInfo) GetDeleteTime() uint32 {
	if x != nil {
		return x.DeleteTime
	}
	return 0
}

// 帖子创建
type CommunityCreatePostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    uint32   `protobuf:"varint,3,opt,name=User_id,json=UserId,proto3" json:"User_id,omitempty"`
	Content   string   `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	ImageUrls []string `protobuf:"bytes,2,rep,name=Image_urls,json=ImageUrls,proto3" json:"Image_urls,omitempty"`
}

func (x *CommunityCreatePostRequest) Reset() {
	*x = CommunityCreatePostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_community_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommunityCreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityCreatePostRequest) ProtoMessage() {}

func (x *CommunityCreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_community_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityCreatePostRequest.ProtoReflect.Descriptor instead.
func (*CommunityCreatePostRequest) Descriptor() ([]byte, []int) {
	return file_rpc_community_proto_rawDescGZIP(), []int{1}
}

func (x *CommunityCreatePostRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CommunityCreatePostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommunityCreatePostRequest) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

type CommunityCreatePostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 可以添加一些返回信息字段，比如返回的帖子ID等
	PostId uint32 `protobuf:"varint,1,opt,name=PostId,proto3" json:"PostId,omitempty"`
}

func (x *CommunityCreatePostResponse) Reset() {
	*x = CommunityCreatePostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_community_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommunityCreatePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityCreatePostResponse) ProtoMessage() {}

func (x *CommunityCreatePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_community_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityCreatePostResponse.ProtoReflect.Descriptor instead.
func (*CommunityCreatePostResponse) Descriptor() ([]byte, []int) {
	return file_rpc_community_proto_rawDescGZIP(), []int{2}
}

func (x *CommunityCreatePostResponse) GetPostId() uint32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

// 帖子删除
type CommunityDelPostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId uint32 `protobuf:"varint,1,opt,name=PostId,proto3" json:"PostId,omitempty"`
}

func (x *CommunityDelPostRequest) Reset() {
	*x = CommunityDelPostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_community_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommunityDelPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityDelPostRequest) ProtoMessage() {}

func (x *CommunityDelPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_community_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityDelPostRequest.ProtoReflect.Descriptor instead.
func (*CommunityDelPostRequest) Descriptor() ([]byte, []int) {
	return file_rpc_community_proto_rawDescGZIP(), []int{3}
}

func (x *CommunityDelPostRequest) GetPostId() uint32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type CommunityDelPostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CommunityDelPostResponse) Reset() {
	*x = CommunityDelPostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_community_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommunityDelPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityDelPostResponse) ProtoMessage() {}

func (x *CommunityDelPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_community_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityDelPostResponse.ProtoReflect.Descriptor instead.
func (*CommunityDelPostResponse) Descriptor() ([]byte, []int) {
	return file_rpc_community_proto_rawDescGZIP(), []int{4}
}

// 查看自己的所有帖子
type CommunityLookPostByOwnRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint32 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
}

func (x *CommunityLookPostByOwnRequest) Reset() {
	*x = CommunityLookPostByOwnRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_community_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommunityLookPostByOwnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityLookPostByOwnRequest) ProtoMessage() {}

func (x *CommunityLookPostByOwnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_community_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityLookPostByOwnRequest.ProtoReflect.Descriptor instead.
func (*CommunityLookPostByOwnRequest) Descriptor() ([]byte, []int) {
	return file_rpc_community_proto_rawDescGZIP(), []int{5}
}

func (x *CommunityLookPostByOwnRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CommunityLookPostByOwnResponses struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostData []*PostInfo `protobuf:"bytes,1,rep,name=PostData,proto3" json:"PostData,omitempty"`
}

func (x *CommunityLookPostByOwnResponses) Reset() {
	*x = CommunityLookPostByOwnResponses{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_community_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommunityLookPostByOwnResponses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityLookPostByOwnResponses) ProtoMessage() {}

func (x *CommunityLookPostByOwnResponses) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_community_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityLookPostByOwnResponses.ProtoReflect.Descriptor instead.
func (*CommunityLookPostByOwnResponses) Descriptor() ([]byte, []int) {
	return file_rpc_community_proto_rawDescGZIP(), []int{6}
}

func (x *CommunityLookPostByOwnResponses) GetPostData() []*PostInfo {
	if x != nil {
		return x.PostData
	}
	return nil
}

// 用户查看所有的帖子
type CommunityLookAllPostsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CommunityLookAllPostsRequest) Reset() {
	*x = CommunityLookAllPostsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_community_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommunityLookAllPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityLookAllPostsRequest) ProtoMessage() {}

func (x *CommunityLookAllPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_community_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityLookAllPostsRequest.ProtoReflect.Descriptor instead.
func (*CommunityLookAllPostsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_community_proto_rawDescGZIP(), []int{7}
}

type CommunityLookAllPostsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostData []*PostInfo `protobuf:"bytes,1,rep,name=PostData,proto3" json:"PostData,omitempty"`
}

func (x *CommunityLookAllPostsResponse) Reset() {
	*x = CommunityLookAllPostsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_community_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommunityLookAllPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityLookAllPostsResponse) ProtoMessage() {}

func (x *CommunityLookAllPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_community_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityLookAllPostsResponse.ProtoReflect.Descriptor instead.
func (*CommunityLookAllPostsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_community_proto_rawDescGZIP(), []int{8}
}

func (x *CommunityLookAllPostsResponse) GetPostData() []*PostInfo {
	if x != nil {
		return x.PostData
	}
	return nil
}

var File_rpc_community_proto protoreflect.FileDescriptor

var file_rpc_community_proto_rawDesc = []byte{
	0x0a, 0x13, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79,
	0x22, 0xc9, 0x01, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x4c, 0x69, 0x6b, 0x65, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x4c, 0x69, 0x6b, 0x65, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x09, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x73, 0x12, 0x1e, 0x0a, 0x0a,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x6e, 0x0a, 0x1a,
	0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50,
	0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x55, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x09, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x73, 0x22, 0x35, 0x0a, 0x1b,
	0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50,
	0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x50,
	0x6f, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x50, 0x6f, 0x73,
	0x74, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x17, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79,
	0x44, 0x65, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x22, 0x1a, 0x0a, 0x18, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e,
	0x69, 0x74, 0x79, 0x44, 0x65, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x37, 0x0a, 0x1d, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x4c,
	0x6f, 0x6f, 0x6b, 0x50, 0x6f, 0x73, 0x74, 0x42, 0x79, 0x4f, 0x77, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x52, 0x0a, 0x1f, 0x43,
	0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x4c, 0x6f, 0x6f, 0x6b, 0x50, 0x6f, 0x73, 0x74,
	0x42, 0x79, 0x4f, 0x77, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x12, 0x2f,
	0x0a, 0x08, 0x50, 0x6f, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x2e, 0x50, 0x6f, 0x73,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x50, 0x6f, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x22,
	0x1e, 0x0a, 0x1c, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x4c, 0x6f, 0x6f, 0x6b,
	0x41, 0x6c, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x50, 0x0a, 0x1d, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x4c, 0x6f, 0x6f, 0x6b,
	0x41, 0x6c, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2f, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x2e, 0x50,
	0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x50, 0x6f, 0x73, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x32, 0xaa, 0x03, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x12,
	0x64, 0x0a, 0x13, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x25, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69,
	0x74, 0x79, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e,
	0x69, 0x74, 0x79, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5b, 0x0a, 0x10, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69,
	0x74, 0x79, 0x44, 0x65, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x22, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x75, 0x6e, 0x69, 0x74, 0x79, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x44,
	0x65, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e,
	0x69, 0x74, 0x79, 0x44, 0x65, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x6e, 0x0a, 0x16, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x4c,
	0x6f, 0x6f, 0x6b, 0x50, 0x6f, 0x73, 0x74, 0x42, 0x79, 0x4f, 0x77, 0x6e, 0x12, 0x28, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69,
	0x74, 0x79, 0x4c, 0x6f, 0x6f, 0x6b, 0x50, 0x6f, 0x73, 0x74, 0x42, 0x79, 0x4f, 0x77, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69,
	0x74, 0x79, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x4c, 0x6f, 0x6f, 0x6b,
	0x50, 0x6f, 0x73, 0x74, 0x42, 0x79, 0x4f, 0x77, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x73, 0x12, 0x6a, 0x0a, 0x15, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x4c,
	0x6f, 0x6f, 0x6b, 0x41, 0x6c, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x12, 0x27, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74,
	0x79, 0x4c, 0x6f, 0x6f, 0x6b, 0x41, 0x6c, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x4c, 0x6f, 0x6f, 0x6b, 0x41, 0x6c,
	0x6c, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0d,
	0x5a, 0x0b, 0x2e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_community_proto_rawDescOnce sync.Once
	file_rpc_community_proto_rawDescData = file_rpc_community_proto_rawDesc
)

func file_rpc_community_proto_rawDescGZIP() []byte {
	file_rpc_community_proto_rawDescOnce.Do(func() {
		file_rpc_community_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_community_proto_rawDescData)
	})
	return file_rpc_community_proto_rawDescData
}

var file_rpc_community_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_rpc_community_proto_goTypes = []interface{}{
	(*PostInfo)(nil),                        // 0: community.PostInfo
	(*CommunityCreatePostRequest)(nil),      // 1: community.CommunityCreatePostRequest
	(*CommunityCreatePostResponse)(nil),     // 2: community.CommunityCreatePostResponse
	(*CommunityDelPostRequest)(nil),         // 3: community.CommunityDelPostRequest
	(*CommunityDelPostResponse)(nil),        // 4: community.CommunityDelPostResponse
	(*CommunityLookPostByOwnRequest)(nil),   // 5: community.CommunityLookPostByOwnRequest
	(*CommunityLookPostByOwnResponses)(nil), // 6: community.CommunityLookPostByOwnResponses
	(*CommunityLookAllPostsRequest)(nil),    // 7: community.CommunityLookAllPostsRequest
	(*CommunityLookAllPostsResponse)(nil),   // 8: community.CommunityLookAllPostsResponse
}
var file_rpc_community_proto_depIdxs = []int32{
	0, // 0: community.CommunityLookPostByOwnResponses.PostData:type_name -> community.PostInfo
	0, // 1: community.CommunityLookAllPostsResponse.PostData:type_name -> community.PostInfo
	1, // 2: community.Community.CommunityCreatePost:input_type -> community.CommunityCreatePostRequest
	3, // 3: community.Community.CommunityDelPost:input_type -> community.CommunityDelPostRequest
	5, // 4: community.Community.CommunityLookPostByOwn:input_type -> community.CommunityLookPostByOwnRequest
	7, // 5: community.Community.CommunityLookAllPosts:input_type -> community.CommunityLookAllPostsRequest
	2, // 6: community.Community.CommunityCreatePost:output_type -> community.CommunityCreatePostResponse
	4, // 7: community.Community.CommunityDelPost:output_type -> community.CommunityDelPostResponse
	6, // 8: community.Community.CommunityLookPostByOwn:output_type -> community.CommunityLookPostByOwnResponses
	8, // 9: community.Community.CommunityLookAllPosts:output_type -> community.CommunityLookAllPostsResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_community_proto_init() }
func file_rpc_community_proto_init() {
	if File_rpc_community_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_community_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_community_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommunityCreatePostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_community_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommunityCreatePostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_community_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommunityDelPostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_community_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommunityDelPostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_community_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommunityLookPostByOwnRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_community_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommunityLookPostByOwnResponses); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_community_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommunityLookAllPostsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_community_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommunityLookAllPostsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_community_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_community_proto_goTypes,
		DependencyIndexes: file_rpc_community_proto_depIdxs,
		MessageInfos:      file_rpc_community_proto_msgTypes,
	}.Build()
	File_rpc_community_proto = out.File
	file_rpc_community_proto_rawDesc = nil
	file_rpc_community_proto_goTypes = nil
	file_rpc_community_proto_depIdxs = nil
}
