// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.11.2
// source: rpc/grow.proto

package grow

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Grow_StartCheck_FullMethodName          = "/group.Grow/StartCheck"
	Grow_CreateRecord_FullMethodName        = "/group.Grow/CreateRecord"
	Grow_LookRecordByUserId_FullMethodName  = "/group.Grow/LookRecordByUserId"
	Grow_CheckPunchCardModel_FullMethodName = "/group.Grow/CheckPunchCardModel"
	Grow_CheckIn_FullMethodName             = "/group.Grow/CheckIn"
)

// GrowClient is the client API for Grow service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrowClient interface {
	// 开启签到
	StartCheck(ctx context.Context, in *StartCheckRequest, opts ...grpc.CallOption) (*StartCheckResponse, error)
	// 上传书法记录
	CreateRecord(ctx context.Context, in *CreateRecordRequest, opts ...grpc.CallOption) (*CreateRecordResponse, error)
	// 查看某人的书法记录
	LookRecordByUserId(ctx context.Context, in *LookRecordByUserIdRequest, opts ...grpc.CallOption) (*LookRecordByUserIdResponse, error)
	// 检查打卡模式是否开启
	CheckPunchCardModel(ctx context.Context, in *CheckPunchCardModelRequest, opts ...grpc.CallOption) (*CheckPunchCardModelResponse, error)
	// 进行打卡
	CheckIn(ctx context.Context, in *CheckInRequest, opts ...grpc.CallOption) (*CheckInResponse, error)
}

type growClient struct {
	cc grpc.ClientConnInterface
}

func NewGrowClient(cc grpc.ClientConnInterface) GrowClient {
	return &growClient{cc}
}

func (c *growClient) StartCheck(ctx context.Context, in *StartCheckRequest, opts ...grpc.CallOption) (*StartCheckResponse, error) {
	out := new(StartCheckResponse)
	err := c.cc.Invoke(ctx, Grow_StartCheck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *growClient) CreateRecord(ctx context.Context, in *CreateRecordRequest, opts ...grpc.CallOption) (*CreateRecordResponse, error) {
	out := new(CreateRecordResponse)
	err := c.cc.Invoke(ctx, Grow_CreateRecord_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *growClient) LookRecordByUserId(ctx context.Context, in *LookRecordByUserIdRequest, opts ...grpc.CallOption) (*LookRecordByUserIdResponse, error) {
	out := new(LookRecordByUserIdResponse)
	err := c.cc.Invoke(ctx, Grow_LookRecordByUserId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *growClient) CheckPunchCardModel(ctx context.Context, in *CheckPunchCardModelRequest, opts ...grpc.CallOption) (*CheckPunchCardModelResponse, error) {
	out := new(CheckPunchCardModelResponse)
	err := c.cc.Invoke(ctx, Grow_CheckPunchCardModel_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *growClient) CheckIn(ctx context.Context, in *CheckInRequest, opts ...grpc.CallOption) (*CheckInResponse, error) {
	out := new(CheckInResponse)
	err := c.cc.Invoke(ctx, Grow_CheckIn_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrowServer is the server API for Grow service.
// All implementations must embed UnimplementedGrowServer
// for forward compatibility
type GrowServer interface {
	// 开启签到
	StartCheck(context.Context, *StartCheckRequest) (*StartCheckResponse, error)
	// 上传书法记录
	CreateRecord(context.Context, *CreateRecordRequest) (*CreateRecordResponse, error)
	// 查看某人的书法记录
	LookRecordByUserId(context.Context, *LookRecordByUserIdRequest) (*LookRecordByUserIdResponse, error)
	// 检查打卡模式是否开启
	CheckPunchCardModel(context.Context, *CheckPunchCardModelRequest) (*CheckPunchCardModelResponse, error)
	// 进行打卡
	CheckIn(context.Context, *CheckInRequest) (*CheckInResponse, error)
	mustEmbedUnimplementedGrowServer()
}

// UnimplementedGrowServer must be embedded to have forward compatible implementations.
type UnimplementedGrowServer struct {
}

func (UnimplementedGrowServer) StartCheck(context.Context, *StartCheckRequest) (*StartCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartCheck not implemented")
}
func (UnimplementedGrowServer) CreateRecord(context.Context, *CreateRecordRequest) (*CreateRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRecord not implemented")
}
func (UnimplementedGrowServer) LookRecordByUserId(context.Context, *LookRecordByUserIdRequest) (*LookRecordByUserIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LookRecordByUserId not implemented")
}
func (UnimplementedGrowServer) CheckPunchCardModel(context.Context, *CheckPunchCardModelRequest) (*CheckPunchCardModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckPunchCardModel not implemented")
}
func (UnimplementedGrowServer) CheckIn(context.Context, *CheckInRequest) (*CheckInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckIn not implemented")
}
func (UnimplementedGrowServer) mustEmbedUnimplementedGrowServer() {}

// UnsafeGrowServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrowServer will
// result in compilation errors.
type UnsafeGrowServer interface {
	mustEmbedUnimplementedGrowServer()
}

func RegisterGrowServer(s grpc.ServiceRegistrar, srv GrowServer) {
	s.RegisterService(&Grow_ServiceDesc, srv)
}

func _Grow_StartCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrowServer).StartCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grow_StartCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrowServer).StartCheck(ctx, req.(*StartCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grow_CreateRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrowServer).CreateRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grow_CreateRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrowServer).CreateRecord(ctx, req.(*CreateRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grow_LookRecordByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookRecordByUserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrowServer).LookRecordByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grow_LookRecordByUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrowServer).LookRecordByUserId(ctx, req.(*LookRecordByUserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grow_CheckPunchCardModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPunchCardModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrowServer).CheckPunchCardModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grow_CheckPunchCardModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrowServer).CheckPunchCardModel(ctx, req.(*CheckPunchCardModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grow_CheckIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrowServer).CheckIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grow_CheckIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrowServer).CheckIn(ctx, req.(*CheckInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Grow_ServiceDesc is the grpc.ServiceDesc for Grow service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Grow_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "group.Grow",
	HandlerType: (*GrowServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartCheck",
			Handler:    _Grow_StartCheck_Handler,
		},
		{
			MethodName: "CreateRecord",
			Handler:    _Grow_CreateRecord_Handler,
		},
		{
			MethodName: "LookRecordByUserId",
			Handler:    _Grow_LookRecordByUserId_Handler,
		},
		{
			MethodName: "CheckPunchCardModel",
			Handler:    _Grow_CheckPunchCardModel_Handler,
		},
		{
			MethodName: "CheckIn",
			Handler:    _Grow_CheckIn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/grow.proto",
}
